In [58]:
#MovieLens
#Importing required libraries
import pandas as pd
import numpy as np

#Ratings File

In [33]:
#import csv file
ratings = pd.read_csv('/Users/gaddamnitish/Desktop/appsheet/ml-latest-small/ratings.csv')
#Checking column names 
list(ratings)

['userId', 'movieId', 'rating', 'timestamp']

In [34]:
#First 5 rows of ratings data frame
ratings.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

#Movies file

In [35]:
movies = pd.read_csv('/Users/gaddamnitish/Desktop/appsheet/ml-latest-small/movies.csv')
list(movies)

['movieId', 'title', 'genres']

In [36]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

#Tags File

In [42]:
tags = pd.read_csv('/Users/gaddamnitish/Desktop/appsheet/ml-latest-small/tags.csv')
list(tags)

['userId', 'movieId', 'tag', 'timestamp']

In [43]:
tags.head()

   userId  movieId                      tag   timestamp
0      15      339  sandra 'boring' bullock  1138537770
1      15     1955                  dentist  1193435061
2      15     7478                 Cambodia  1170560997
3      15    32892                  Russian  1170626366
4      15    34162              forgettable  1141391765

#Links File

In [44]:
links = pd.read_csv('/Users/gaddamnitish/Desktop/appsheet/ml-latest-small/links.csv')
list(links)

['movieId', 'imdbId', 'tmdbId']

In [45]:
links.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

The First Question needs info from both ratings and movies csv's. Hence merging both the files.

In [49]:
# create one merged DataFrame
movie_rating = pd.merge(ratings, movies)

In [52]:
#First 5 rows of merged file
movie_rating.head()

   userId  movieId  rating   timestamp                   title genres
0       1       31     2.5  1260759144  Dangerous Minds (1995)  Drama
1       7       31     3.0   851868750  Dangerous Minds (1995)  Drama
2      31       31     4.0  1273541953  Dangerous Minds (1995)  Drama
3      32       31     4.0   834828440  Dangerous Minds (1995)  Drama
4      36       31     3.0   847057202  Dangerous Minds (1995)  Drama

In [158]:
#Trying to list first 5 only movies in Crime Genre
movie_crime = movie_rating[movie_rating['genres'] == 'Crime']
movie_crime.head()

#most_rated_crime = movie_crime.groupby('title').agg({'rating': [np.size, np.mean]})
#most_rated_crime[movie_crime].sort_values([('rating', 'mean')], ascending=False)[:25]

#movie_stats = movie_rating.groupby(['title','genres']).agg({'rating': [np.size, np.mean]})
#movie_stats['genres'] = 'Musical'
#atleast_100 = movie_stats['rating']['size'] >= 100
#movie_crime = movie_stats['genres'] == 'Crime'
#movie_stats[atleast_100].sort_values([('rating', 'mean')], ascending=False)[:25]

#Trying to list last 5 only movies in Crime Genre
#movie_rating[movie_rating['genres'] == 'Drama'].tail(5)

       userId  movieId  rating  timestamp                title genres
90637     119     2425     3.0  952583624  General, The (1998)  Crime
90638     388     2425     4.0  965182119  General, The (1998)  Crime
90639     472     2425     3.0  939141157  General, The (1998)  Crime
90640     509     2425     4.0  946268745  General, The (1998)  Crime
90641     608     2425     4.0  958825030  General, The (1998)  Crime

In [119]:
#Trying to understand how the groupby function works.
#Printing out all the columns of the first 5 movies in each Genre

movie_rating.groupby('genres').head()

#***Should I split the '|' between the genres?***

,userId,movieId,rating,timestamp,title,genres
0,1,31,2.5,1260759144,Dangerous Minds (1995),Drama
1,7,31,3.0,851868750,Dangerous Minds (1995),Drama
2,31,31,4.0,1273541953,Dangerous Minds (1995),Drama
3,32,31,4.0,834828440,Dangerous Minds (1995),Drama
4,36,31,3.0,847057202,Dangerous Minds (1995),Drama
42,1,1029,3.0,1260759179,Dumbo (1941),Animation|Children|Drama|Musical
43,19,1029,5.0,855192033,Dumbo (1941),Animation|Children|Drama|Musical
44,35,1029,1.5,1174450070,Dumbo (1941),Animation|Children|Drama|Musical
45,61,1029,2.5,1216487645,Dumbo (1941),Animation|Children|Drama|Musical
46,73,1029,3.0,1256030424,Dumbo (1941),Animation|Children|Drama|Musical
84,1,1061,3.0,1260759182,Sleepers (1996),Thriller
85,19,1061,3.0,855190382,Sleepers (1996),Thriller
86,23,1061,3.5,1148673456,Sleepers (1996),Thriller
87,30,1061,3.0,946162006,Sleepers (1996),Thriller
88,70,1061,5.0,853955020,Sleepers (1996),Thriller
117,1,1129,2.0,1260759185,Escape from New York (1981),Action|Adventure|Sci-Fi|Thriller
118,7,1129,3.0,851869103,Escape from New York (1981),Action|Adventure|Sci-Fi|Thriller
119,19,1129,3.0,855192347,Escape from New York (1981),Action|Adventure|Sci-Fi|Thriller
120,21,1129,3.0,853848738,Escape from New York (1981),Action|Adventure|Sci-Fi|Thriller
121,30,1129,3.0,945294508,Escape from New York (1981),Action|Adventure|Sci-Fi|Thriller
211,1,1263,2.0,1260759151,"Deer Hunter, The (1978)",Drama|War
212,15,1263,4.0,1120208625,"Deer Hunter, The (1978)",Drama|War
213,17,1263,4.5,1127470072,"Deer Hunter, The (1978)",Drama|War
214,19,1263,4.0,855191775,"Deer Hunter, The (1978)",Drama|War
215,21,1263,4.0,853851203,"Deer Hunter, The (1978)",Drama|War
259,1,1287,2.0,1260759187,Ben-Hur (1959),Action|Adventure|Drama
260,7,1287,4.0,851868332,Ben-Hur (1959),Action|Adventure|Drama
261,15,1287,2.0,1033345087,Ben-Hur (1959),Action|Adventure|Drama
262,19,1287,4.0,855192517,Ben-Hur (1959),Action|Adventure|Drama
263,21,1287,5.0,853850791,Ben-Hur (1959),Action|Adventure|Drama
...,...,...,...,...,...,...
99336,572,34435,4.5,1436466688,Sholay (1975),Action|Adventure|Comedy|Musical|Romance|Thriller
99369,576,4445,3.0,1005426654,T-Rex: Back to the Cretaceous (1998),Adventure|Documentary|IMAX
99370,581,4445,0.5,1259725946,T-Rex: Back to the Cretaceous (1998),Adventure|Documentary|IMAX
99385,580,5041,3.0,1165291244,Fire and Ice (1983),Animation|Fantasy
99386,580,5042,1.0,1217951137,Forbidden Zone (1980),Musical|Sci-Fi
99387,580,6966,2.5,1156128550,Darkman (1990),Action|Crime|Fantasy|Sci-Fi|Thriller
99388,652,6966,4.5,1440271768,Darkman (1990),Action|Crime|Fantasy|Sci-Fi|Thriller
99405,580,27441,3.0,1269893791,Blood: The Last Vampire (2000),Action|Animation|Horror
99414,580,51709,4.0,1278941599,"Host, The (Gwoemul) (2006)",Comedy|Drama|Horror|Sci-Fi|Thriller
99415,664,51709,4.0,1343764123,"Host, The (Gwoemul) (2006)",Comedy|Drama|Horror|Sci-Fi|Thriller
99428,580,74438,2.0,1269894511,Legend of the Red Dragon (a.k.a. New Legend of...,Action|Adventure|Comedy|Drama|Romance
99574,620,72294,4.0,1455531907,"Christmas Carol, A (2009)",Animation|Children|Drama|Fantasy|IMAX
99613,624,6798,3.0,1064153909,Bugsy Malone (1976),Children|Comedy|Crime|Musical
99624,624,8136,0.5,1262267722,Indestructible Man (1956),Crime|Horror|Sci-Fi
99627,624,8743,2.5,1091720265,Biggles (1986),Adventure|Fantasy|Sci-Fi
99656,624,82093,1.5,1328371086,London Boulevard (2010),Crime|Romance
99669,624,90522,2.0,1356205855,Johnny English Reborn (2011),Adventure|Comedy|Thriller
99673,624,91273,1.5,1347100087,Bunraku (2010),Action|Drama|Fantasy
99740,624,104129,2.0,1430057625,Man of Tai Chi (2013),Action|IMAX
99848,624,146688,2.0,1472820632,Solace (2015),Fantasy|Mystery|Thriller
99866,648,6690,3.5,1138479546,Don't Tempt Me (Sin noticias de Dios) (2001),Comedy|Fantasy|Mystery
99876,648,27875,4.0,1199049186,Redemption: The Stan Tookie Williams Story (2004),Crime|Documentary|Drama
99882,648,49265,4.0,1201993174,Shooting Dogs (a.k.a. Beyond the Gates) (2005),Documentary|Drama|War
99897,648,140152,4.0,1460757570,Dreamcatcher (2015),Children|Crime|Documentary
99919,652,26791,5.0,1439588577,Shining Through (1992),Drama|Romance|Thriller|War
99927,652,68835,4.5,1442082655,Were the World Mine (2008),Adventure|Fantasy|Musical|Romance
99949,652,110781,4.0,1442084222,Mulan II (2004),Action|Animation|Children|Comedy|Musical
99957,652,135266,4.0,1442696469,Zenon: The Zequel (2001),Adventure|Children|Comedy|Sci-Fi
99981,653,2103,3.0,948161066,Tall Tale (1995),Adventure|Children|Fantasy|Western
100000,664,72380,3.5,1344435977,"Box, The (2009)",Drama|Horror|Mystery|Sci-Fi|Thriller

In [74]:
#What are the 25 most rated movies by total voting size?

most_rated = movie_rating.groupby('title').size().sort_values(ascending=False)[:25]
most_rated

title
Forrest Gump (1994)                                                               341
Pulp Fiction (1994)                                                               324
Shawshank Redemption, The (1994)                                                  311
Silence of the Lambs, The (1991)                                                  304
Star Wars: Episode IV - A New Hope (1977)                                         291
Jurassic Park (1993)                                                              274
Matrix, The (1999)                                                                259
Toy Story (1995)                                                                  247
Schindler's List (1993)                                                           244
Terminator 2: Judgment Day (1991)                                                 237
Star Wars: Episode V - The Empire Strikes Back (1980)                             234
Braveheart (1995)                                                                 228
Back to the Future (1985)                                                         226
Fargo (1996)                                                                      224
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)    220
American Beauty (1999)                                                            220
Independence Day (a.k.a. ID4) (1996)                                              218
Star Wars: Episode VI - Return of the Jedi (1983)                                 217
Aladdin (1992)                                                                    215
Fugitive, The (1993)                                                              213
Dances with Wolves (1990)                                                         202
Fight Club (1999)                                                                 202
Seven (a.k.a. Se7en) (1995)                                                       201
Usual Suspects, The (1995)                                                        201
Apollo 13 (1995)                                                                  200
dtype: int64

In [126]:
#What are the 25 most rated movies when considering the mean of the rating?

movie_stats = movie_rating.groupby('title').agg({'rating': [np.size, np.mean]})
atleast_100 = movie_stats['rating']['size'] >= 100
movie_stats[atleast_100].sort_values([('rating', 'mean')], ascending=False)[:25]

                                                   rating
                                                     size      mean
title
Godfather, The (1972)                               200.0  4.487500
Shawshank Redemption, The (1994)                    311.0  4.487138
Godfather: Part II, The (1974)                      135.0  4.385185
Usual Suspects, The (1995)                          201.0  4.370647
Schindler's List (1993)                             244.0  4.303279
One Flew Over the Cuckoo's Nest (1975)              144.0  4.256944
Fargo (1996)                                        224.0  4.256696
Pulp Fiction (1994)                                 324.0  4.256173
American Beauty (1999)                              220.0  4.236364
Dark Knight, The (2008)                             121.0  4.235537
Casablanca (1942)                                   117.0  4.235043
Star Wars: Episode V - The Empire Strikes Back ...  234.0  4.232906
Memento (2000)                                      132.0  4.227273
Taxi Driver (1976)                                  118.0  4.224576
Monty Python and the Holy Grail (1975)              145.0  4.224138
Star Wars: Episode IV - A New Hope (1977)           291.0  4.221649
Dr. Strangelove or: How I Learned to Stop Worry...  105.0  4.209524
Princess Bride, The (1987)                          163.0  4.208589
Goodfellas (1990)                                   131.0  4.202290
Raiders of the Lost Ark (Indiana Jones and the ...  220.0  4.193182
Matrix, The (1999)                                  259.0  4.183398
Lord of the Rings: The Fellowship of the Ring, ...  200.0  4.182500
Fight Club (1999)                                   202.0  4.178218
Reservoir Dogs (1992)                               132.0  4.162879
Amadeus (1984)                                      100.0  4.155000

In [114]:
#Grouping the above query by genre

movie_stats = movie_rating.groupby(['genres', 'title']).agg({'rating': [np.size, np.mean]})
atleast_100 = movie_stats['rating']['size'] >= 100
movie_stats[atleast_100].sort_values([('rating', 'mean')], ascending=False)[:50]

                                                                                                   rating  \
                                                                                                     size
genres                                          title
Crime|Drama                                     Godfather, The (1972)                               200.0
                                                Shawshank Redemption, The (1994)                    311.0
                                                Godfather: Part II, The (1974)                      135.0
Crime|Mystery|Thriller                          Usual Suspects, The (1995)                          201.0
Drama|War                                       Schindler's List (1993)                             244.0
Drama                                           One Flew Over the Cuckoo's Nest (1975)              144.0
Comedy|Crime|Drama|Thriller                     Fargo (1996)                                        224.0
                                                Pulp Fiction (1994)                                 324.0
Drama|Romance                                   American Beauty (1999)                              220.0
Action|Crime|Drama|IMAX                         Dark Knight, The (2008)                             121.0
Drama|Romance                                   Casablanca (1942)                                   117.0
Action|Adventure|Sci-Fi                         Star Wars: Episode V - The Empire Strikes Back ...  234.0
Mystery|Thriller                                Memento (2000)                                      132.0
Crime|Drama|Thriller                            Taxi Driver (1976)                                  118.0
Adventure|Comedy|Fantasy                        Monty Python and the Holy Grail (1975)              145.0
Action|Adventure|Sci-Fi                         Star Wars: Episode IV - A New Hope (1977)           291.0
Comedy|War                                      Dr. Strangelove or: How I Learned to Stop Worry...  105.0
Action|Adventure|Comedy|Fantasy|Romance         Princess Bride, The (1987)                          163.0
Crime|Drama                                     Goodfellas (1990)                                   131.0
Action|Adventure                                Raiders of the Lost Ark (Indiana Jones and the ...  220.0
Action|Sci-Fi|Thriller                          Matrix, The (1999)                                  259.0
Adventure|Fantasy                               Lord of the Rings: The Fellowship of the Ring, ...  200.0
Action|Crime|Drama|Thriller                     Fight Club (1999)                                   202.0
Crime|Mystery|Thriller                          Reservoir Dogs (1992)                               132.0
Drama                                           Amadeus (1984)                                      100.0
Comedy|Crime|Drama                              Trainspotting (1996)                                124.0
Drama|Romance                                   Good Will Hunting (1997)                            157.0
Action|Drama|War                                Apocalypse Now (1979)                               112.0
Crime|Horror|Thriller                           Silence of the Lambs, The (1991)                    304.0
Action|Adventure|Drama|Fantasy                  Lord of the Rings: The Return of the King, The ...  176.0
Drama|Romance|Sci-Fi                            Eternal Sunshine of the Spotless Mind (2004)        106.0
Crime|Film-Noir|Mystery|Thriller                L.A. Confidential (1997)                            125.0
Comedy|Romance                                  Amelie (Fabuleux destin d'Amélie Poulain, Le) (...  125.0
Adventure|Drama                                 Stand by Me (1986)                                  112.0
Action|Crime|Drama|Thriller                     Léon: The Professional (a.k.a. The Professional...  132.0
Adventure|Fantasy                               Lord of the Rings: The Two Towers, The (2002)       188.0
Action|Adventure|Sci-Fi                         Star Wars: Episode VI - Return of the Jedi (1983)   217.0
Comedy|Drama|Romance|War                        Forrest Gump (1994)                                 341.0
Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX Inception (2010)                                    111.0
Action|Sci-Fi|Thriller                          Blade Runner (1982)                                 146.0
Mystery|Thriller                                Seven (a.k.a. Se7en) (1995)                         201.0
Drama|War                                       Full Metal Jacket (1987)                            104.0
Horror                                          Shining, The (1980)                                 101.0
Crime|Drama                                     American History X (1998)                           107.0
Drama|Horror|Mystery                            Sixth Sense, The (1999)                             193.0
Action|Adventure                                Indiana Jones and the Last Crusade (1989)           147.0
Adventure|Comedy|Sci-Fi                         Back to the Future (1985)                           226.0
Comedy                                          Ferris Bueller's Day Off (1986)                     133.0
Action|Sci-Fi                                   Terminator 2: Judgment Day (1991)                   237.0
Crime|Drama|Sci-Fi|Thriller                     Clockwork Orange, A (1971)                          121.0


                                                                                                        mean
genres                                          title
Crime|Drama                                     Godfather, The (1972)                               4.487500
                                                Shawshank Redemption, The (1994)                    4.487138
                                                Godfather: Part II, The (1974)                      4.385185
Crime|Mystery|Thriller                          Usual Suspects, The (1995)                          4.370647
Drama|War                                       Schindler's List (1993)                             4.303279
Drama                                           One Flew Over the Cuckoo's Nest (1975)              4.256944
Comedy|Crime|Drama|Thriller                     Fargo (1996)                                        4.256696
                                                Pulp Fiction (1994)                                 4.256173
Drama|Romance                                   American Beauty (1999)                              4.236364
Action|Crime|Drama|IMAX                         Dark Knight, The (2008)                             4.235537
Drama|Romance                                   Casablanca (1942)                                   4.235043
Action|Adventure|Sci-Fi                         Star Wars: Episode V - The Empire Strikes Back ...  4.232906
Mystery|Thriller                                Memento (2000)                                      4.227273
Crime|Drama|Thriller                            Taxi Driver (1976)                                  4.224576
Adventure|Comedy|Fantasy                        Monty Python and the Holy Grail (1975)              4.224138
Action|Adventure|Sci-Fi                         Star Wars: Episode IV - A New Hope (1977)           4.221649
Comedy|War                                      Dr. Strangelove or: How I Learned to Stop Worry...  4.209524
Action|Adventure|Comedy|Fantasy|Romance         Princess Bride, The (1987)                          4.208589
Crime|Drama                                     Goodfellas (1990)                                   4.202290
Action|Adventure                                Raiders of the Lost Ark (Indiana Jones and the ...  4.193182
Action|Sci-Fi|Thriller                          Matrix, The (1999)                                  4.183398
Adventure|Fantasy                               Lord of the Rings: The Fellowship of the Ring, ...  4.182500
Action|Crime|Drama|Thriller                     Fight Club (1999)                                   4.178218
Crime|Mystery|Thriller                          Reservoir Dogs (1992)                               4.162879
Drama                                           Amadeus (1984)                                      4.155000
Comedy|Crime|Drama                              Trainspotting (1996)                                4.141129
Drama|Romance                                   Good Will Hunting (1997)                            4.140127
Action|Drama|War                                Apocalypse Now (1979)                               4.138393
Crime|Horror|Thriller                           Silence of the Lambs, The (1991)                    4.138158
Action|Adventure|Drama|Fantasy                  Lord of the Rings: The Return of the King, The ...  4.127841
Drama|Romance|Sci-Fi                            Eternal Sunshine of the Spotless Mind (2004)        4.122642
Crime|Film-Noir|Mystery|Thriller                L.A. Confidential (1997)                            4.120000
Comedy|Romance                                  Amelie (Fabuleux destin d'Amélie Poulain, Le) (...  4.096000
Adventure|Drama                                 Stand by Me (1986)                                  4.093750
Action|Crime|Drama|Thriller                     Léon: The Professional (a.k.a. The Professional...  4.071970
Adventure|Fantasy                               Lord of the Rings: The Two Towers, The (2002)       4.061170
Action|Adventure|Sci-Fi                         Star Wars: Episode VI - Return of the Jedi (1983)   4.059908
Comedy|Drama|Romance|War                        Forrest Gump (1994)                                 4.054252
Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX Inception (2010)                                    4.049550
Action|Sci-Fi|Thriller                          Blade Runner (1982)                                 4.037671
Mystery|Thriller                                Seven (a.k.a. Se7en) (1995)                         4.034826
Drama|War                                       Full Metal Jacket (1987)                            4.033654
Horror                                          Shining, The (1980)                                 4.029703
Crime|Drama                                     American History X (1998)                           4.023364
Drama|Horror|Mystery                            Sixth Sense, The (1999)                             4.018135
Action|Adventure                                Indiana Jones and the Last Crusade (1989)           4.017007
Adventure|Comedy|Sci-Fi                         Back to the Future (1985)                           4.015487
Comedy                                          Ferris Bueller's Day Off (1986)                     4.007519
Action|Sci-Fi                                   Terminator 2: Judgment Day (1991)                   4.006329
Crime|Drama|Sci-Fi|Thriller                     Clockwork Orange, A (1971)                          4.000000